set(CMAKE_CXX_COMPILER mpicxx)

set(MPIEXEC mvp2run)

set(MPIEXEC_NUMPROC_FLAG "-c")

set(EXT_DEFINITIONS "-DMPI_HAO" ${EXT_DEFINITIONS})

set(EXT_FLAGS "-Wall -O3 -march=corei7 -m64 -DNDEBUG ${EXT_FLAGS}")