find_package(MPI REQUIRED)

set(CMAKE_CXX_COMPILER ${MPI_CXX_COMPILER})

set(EXT_DEFINITIONS "-DMPI_HAO" ${EXT_DEFINITIONS})

set(EXT_FLAGS "-Wall ${EXT_FLAGS}")

#FindMPI.cmake defines MPIEXEC and MPIEXEC_NUMPROC_FLAG